### ISSUE TITLE
[Upstream Bug] Dry-run fails if config contains nonexistent teams

### ISSUE THREAD

**Issue by lelia** [uwu-tools/peribolos#216]
## Issue Context

This issue has already been identified and reported upstream: https://github.com/kubernetes/test-infra/issues/26542

## Steps to Reproduce

1. Create an org config YAML containing one or more GitHub Teams which don't yet exist
1. Run Peribolos with the `confirm=false` flag in order to enable dry-run mode
1. Once Peribolos reaches the nonexistent team(s), it will [throw an error](https://github.com/cisco-ospo/.github-private/actions/runs/4834896606/jobs/8616643914) like this: 

```json
{"component":"unset","file":"github.com/uwu-tools/peribolos/cmd/main.go:138","func":"github.com/uwu-tools/peribolos/cmd.rootCmd","level":"fatal","msg":"Configuration failed: failed to configure cisco-ospo teams: failed to update demo-repository-maintainers members: failed to list demo-repository-maintainers(demo-repository-maintainers) members: return code not 2XX: 404 Not Found","severity":"fatal","time":"2023-04-28T21:22:49Z"}
```

## Proposed Workarounds

- **Option 1:** Manually create the teams by hand, using the GitHub UI, then re-run Peribolos. Dry-run should now work as normal.
- **Option 2:** Run Peribolos with dry-mode disabled (`confirm=true`) in order to force team creation. **Note that this option is riskier, as Peribolos will potentially run against un-tested configuration changes!**

## Near-Term Solution

Add a `WARN` level log message in the [relevant codepath](https://github.com/uwu-tools/peribolos/blob/main/org/dump.go#L126-L130) referencing this bug.

**Comment by cpanato** [comment]
@lelia what is the command that you are running? trying to reproduce but I am not seeing the error :/
